=== tivanovic21/orac/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://or.fer.unizg.hr/kafici_restorani.json",
    "type": "array",
    "title": "Kafići i restorani u Hrvatskoj",
    "description": "Skup podataka o kafićima i restoranima u Republici Hrvatskoj.",
    "items": {
        "type": "object",
        "title": "Objekt",
        "description": "Predstavlja kafić ili restoran.",
        "properties": {
            "id_objekta": {
                "type": "number",
                "title": "ID objekta",
                "description": "Jedinstveni identifikator objekta"
            },
            "naziv": {
                "type": "string",
                "title": "Naziv",
                "description": "Naziv objekta"
            },
            "tip_objekta": {
                "type": "string",
                "title": "Tip objekta",
                "description": "Tip objekta (npr. kafić, restoran, pizzeria, ...)"
            },
            "opis": {
                "type": "string",
                "title": "Opis",
                "description": "Kratki opis objekta"
            },
            "prosjecna_ocjena": {
                "type": "number",
                "title": "Prosječna ocjena",
                "description": "Prosječna ocjena objekta"
            },
            "cjenovni_rang": {
                "type": "string",
                "title": "Cjenovni rang",
                "description": "Cjenovni rang objekta (enumeracija $, $$, $$$)"
            },
            "vlasnik": {
                "type": "string",
                "title": "Vlasnik",
                "description": "Ime vlasnika objekta"
            },
            "dostupna_dostava": {
                "type": "boolean",
                "title": "Dostupna dostava",
                "description": "Informacija o dostupnosti dostave"
            },
            "datum_unosa": {
                "type": "string",
                "format": "date-time",
                "title": "Datum unosa",
                "description": "Datum i vrijeme unosa podataka o objektu"
            },
            "kontakt": {
                "type": [
                    "object",
                    "null"
                ],
                "title": "Kontakt",
                "description": "Kontaktni podaci objekta",
                "properties": {
                    "web_stranica": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "title": "Web stranica objekta",
                        "description": "URL web stranice objekta, može predstavljati i socijalnu mrežu"
                    },
                    "kontakt_broj": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "title": "Kontakt broj",
                        "description": "Kontakt broj objekta"
                    },
                    "email": {
                        "type": [
                            "string",
                            "null"
                        ],
                        "title": "Email",
                        "description": "Email adresa objekta"
                    }
                },
                "required": []
            },
            "lokacije": {
                "type": "array",
                "items": {
                    "type": "object",
                    "title": "Lokacija",
                    "description": "Podaci o lokaciji objekta te radnom vremenu na toj lokaciji",
                    "properties": {
                        "ulica": {
                            "type": "string",
                            "title": "Ulica",
                            "description": "Naziv ulice na kojoj se objekt nalazi"
                        },
                        "kucni_broj": {
                            "type": "string",
                            "title": "Kućni broj",
                            "description": "Kućni broj na kojem se objekt nalazi"
                        },
                        "grad": {
                            "type": "string",
                            "title": "Grad",
                            "description": "Naziv grada u kojem se objekt nalazi"
                        },
                        "latitude": {
                            "type": "number",
                            "title": "Geografska širina",
                            "description": "Geografska širina lokacije objekta"
                        },
                        "longitude": {
                            "type": "number",
                            "title": "Geografska dužina",
                            "description": "Geografska dužina lokacije objekta"
                        },
                        "radno_vrijeme": {
                            "type": "string",
                            "title": "Radno vrijeme",
                            "description": "Radno vrijeme objekta na toj lokaciji"
                        }
                    },
                    "required": [
                        "ulica",
                        "kucni_broj",
                        "grad"
                    ]
                }
            },
            "tagovi": {
                "type": [
                    "array",
                    "null"
                ],
                "items": {
                    "type": "object",
                    "title": "Tag",
                    "description": "Oznake dostupnih sadržaja u objektu",
                    "properties": {
                        "naziv": {
                            "type": "string",
                            "title": "Naziv taga",
                            "description": "Naziv oznake"
                        },
                        "opis": {
                            "type": "string",
                            "title": "Opis taga",
                            "description": "Opis oznake"
                        }
                    },
                    "required": [
                        "naziv"
                    ]
                }
            }
        },
        "required": [
            "id_objekta",
            "naziv",
            "tip_objekta",
            "lokacije"
        ]
    }
}

=== tivanovic21/orac/kafici_restorani.json
[
    {
        "id_objekta": 10,
        "naziv": "Program Bar",
        "tip_objekta": "kafić",
        "opis": "This cafe provides you with nice food and a place to rest after a long walk.",
        "prosjecna_ocjena": 4.80,
        "cjenovni_rang": "$",
        "vlasnik": "Saša Žerajić",
        "dostupna_dostava": false,
        "datum_unosa": "2025-10-23T16:28:27.104604",
        "kontakt": {
            "web_stranica": "https://www.instagram.com/program_bar/",
            "kontakt_broj": "+385989938279",
            "email": "program.programbar@gmail.com"
        },
        "lokacije": [
            {
                "ulica": "Martićeva ulica",
                "kucni_broj": "14F",
                "grad": "Zagreb",
                "latitude": 45.81207000,
                "longitude": 15.98930000,
                "radno_vrijeme": "07:00–23:00"
            },
            {
                "ulica": "Petrova ulica",
                "kucni_broj": "21",
                "grad": "Zagreb",
                "latitude": 45.81690300,
                "longitude": 15.99548900,
                "radno_vrijeme": "08:00–23:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "Terasa",
                "opis": "Vanjski prostor za sjedenje"
            },
            {
                "naziv": "Klimatizacija",
                "opis": "Klimatizirani unutarnji prostor"
            },
            {
                "naziv": "Plaćanje karticom",
                "opis": "Prihvaća plaćanje debitnim/kreditnim karticama"
            }
        ]
    },
    {
        "id_objekta": 9,
        "naziv": "Mr. Fogg",
        "tip_objekta": "kafić",
        "opis": "The first steampunk bar in Zagreb.",
        "prosjecna_ocjena": 4.70,
        "cjenovni_rang": "$",
        "vlasnik": "Emil Tocauer",
        "dostupna_dostava": false,
        "datum_unosa": "2025-10-23T16:23:56.099344",
        "kontakt": {
            "web_stranica": "https://www.facebook.com/BarMrFogg",
            "kontakt_broj": "+38516272650",
            "email": "mr.fogg.zagreb@gmail.com"
        },
        "lokacije": [
            {
                "ulica": "Martićeva ulica",
                "kucni_broj": "31",
                "grad": "Zagreb",
                "latitude": 45.81243100,
                "longitude": 15.99149200,
                "radno_vrijeme": "07:00–00:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "Terasa",
                "opis": "Vanjski prostor za sjedenje"
            },
            {
                "naziv": "Plaćanje karticom",
                "opis": "Prihvaća plaćanje debitnim/kreditnim karticama"
            }
        ]
    },
    {
        "id_objekta": 8,
        "naziv": "Botaničar",
        "tip_objekta": "kafić",
        "opis": "Botaničar, a budding flower of creativity on Zagreb’s urban map. Bar with an original botanical twist. Home of arts and crafts, nurturing those little pleasures of life.",
        "prosjecna_ocjena": 4.60,
        "cjenovni_rang": "$",
        "vlasnik": "Marko Krneta",
        "dostupna_dostava": false,
        "datum_unosa": "2025-10-23T16:16:29.797888",
        "kontakt": {
            "web_stranica": "https://www.facebook.com/BotanicarZagreb/",
            "kontakt_broj": null,
            "email": "botanicar.zg@gmail.com"
        },
        "lokacije": [
            {
                "ulica": "Trg Marka Marulića",
                "kucni_broj": "6",
                "grad": "Zagreb",
                "latitude": 45.80627400,
                "longitude": 15.97139700,
                "radno_vrijeme": "08:00–23:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "WiFi",
                "opis": "Besplatan bežični internet za goste"
            },
            {
                "naziv": "Parking",
                "opis": "Dostupan parking prostor"
            },
            {
                "naziv": "Terasa",
                "opis": "Vanjski prostor za sjedenje"
            },
            {
                "naziv": "Plaćanje karticom",
                "opis": "Prihvaća plaćanje debitnim/kreditnim karticama"
            }
        ]
    },
    {
        "id_objekta": 7,
        "naziv": "Krivi Put",
        "tip_objekta": "kafić",
        "opis": "Krivi Put is the place to go to when you feel like avoiding responsibilities.",
        "prosjecna_ocjena": 4.80,
        "cjenovni_rang": "$",
        "vlasnik": "Nenad Barbić",
        "dostupna_dostava": false,
        "datum_unosa": "2025-10-23T16:11:21.053375",
        "kontakt": {
            "web_stranica": "https://www.facebook.com/pages/Krivi-Put/134656319955740",
            "kontakt_broj": "+38514837701",
            "email": null
        },
        "lokacije": [
            {
                "ulica": "Savska cesta",
                "kucni_broj": "14",
                "grad": "Zagreb",
                "latitude": 45.80477600,
                "longitude": 15.96555100,
                "radno_vrijeme": "08:00–00:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "Terasa",
                "opis": "Vanjski prostor za sjedenje"
            },
            {
                "naziv": "Plaćanje karticom",
                "opis": "Prihvaća plaćanje debitnim/kreditnim karticama"
            }
        ]
    },
    {
        "id_objekta": 6,
        "naziv": "Bacchus Jazz Bar",
        "tip_objekta": "kafić",
        "opis": "Laidback jazz sessions, beer & coffee at a cellar bar with a courtyard sheltered by fig trees.",
        "prosjecna_ocjena": 4.70,
        "cjenovni_rang": "$",
        "vlasnik": "Duje Oman",
        "dostupna_dostava": false,
        "datum_unosa": "2025-10-23T16:02:43.649361",
        "kontakt": {
            "web_stranica": "https://www.facebook.com/bacchusjazzbar",
            "kontakt_broj": "+38598322804",
            "email": null
        },
        "lokacije": [
            {
                "ulica": "Trg Kralja Tomislava",
                "kucni_broj": "16",
                "grad": "Zagreb",
                "latitude": 45.80642300,
                "longitude": 15.97769400,
                "radno_vrijeme": "09:00–00:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "Terasa",
                "opis": "Vanjski prostor za sjedenje"
            },
            {
                "naziv": "Plaćanje karticom",
                "opis": "Prihvaća plaćanje debitnim/kreditnim karticama"
            }
        ]
    },
    {
        "id_objekta": 4,
        "naziv": "Kiyomi",
        "tip_objekta": "restoran",
        "opis": "KIYOMI is an Asian restaurant passionate about creating delicious and unique dishes that blend traditional Dim Sum, Robata, and Sushi flavors.",
        "prosjecna_ocjena": 4.80,
        "cjenovni_rang": "$$",
        "vlasnik": "Vid Nikolić",
        "dostupna_dostava": false,
        "datum_unosa": "2025-10-23T15:41:26.470459",
        "kontakt": {
            "web_stranica": "https://www.kiyomi.hr",
            "kontakt_broj": "+38516474897",
            "email": "reservations@kiyomi.hr"
        },
        "lokacije": [
            {
                "ulica": "Gajeva Ulica",
                "kucni_broj": "10",
                "grad": "Zagreb",
                "latitude": 45.81090710,
                "longitude": 15.97638390,
                "radno_vrijeme": "12:00–00:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "WiFi",
                "opis": "Besplatan bežični internet za goste"
            },
            {
                "naziv": "Plaćanje karticom",
                "opis": "Prihvaća plaćanje debitnim/kreditnim karticama"
            },
            {
                "naziv": "Japanska hrana",
                "opis": "Restoran nudi japansku hranu poput sushi-a"
            }
        ]
    },
    {
        "id_objekta": 3,
        "naziv": "Batak",
        "tip_objekta": "restoran",
        "opis": "Najpoznatiji smo po sočnim i ukusnim jelima s roštilja poput nezaobilaznih mazalica, sočnih ćevapa, gurmanske pljeskavice, ili punjene vješalice.",
        "prosjecna_ocjena": 4.60,
        "cjenovni_rang": "$$",
        "vlasnik": "Boris Stojić",
        "dostupna_dostava": true,
        "datum_unosa": "2025-10-23T15:28:57.038325",
        "kontakt": {
            "web_stranica": "https://batak.hr",
            "kontakt_broj": "+38516471111",
            "email": null
        },
        "lokacije": [
            {
                "ulica": "Avenija Većeslava Holjevca",
                "kucni_broj": "62",
                "grad": "Zagreb",
                "latitude": 45.77769852,
                "longitude": 15.97968674,
                "radno_vrijeme": "11:00–23:00"
            },
            {
                "ulica": "Ulica Ivana Tkaličića",
                "kucni_broj": "70",
                "grad": "Zagreb",
                "latitude": 45.81752000,
                "longitude": 15.97626000,
                "radno_vrijeme": "11:00–23:00"
            },
            {
                "ulica": "Ulica Jakova Gotovca",
                "kucni_broj": "1",
                "grad": "Zagreb",
                "latitude": 45.81519300,
                "longitude": 15.99443300,
                "radno_vrijeme": "11:00–23:00"
            },
            {
                "ulica": "Gajeva Ulica",
                "kucni_broj": "10",
                "grad": "Zagreb",
                "latitude": 45.81090700,
                "longitude": 15.97638400,
                "radno_vrijeme": "12:00–00:00"
            }
        ],
        "tagovi": [
            {
                "naziv": "WiFi",
                "opis": "Besplatan bežični internet za goste"
            },
            {
                "naziv": "Parking",
                "opis": "Dostupan parking prostor"
            },
            {
                "naziv": "Terasa",
